name: Build and deploy Azure App Service Environment

on:
    workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Create resource group for app service
              id: resourceGroup
              uses: azure/CLI@v1
              with:
                azcliversion: 2.30.0
                inlineScript: |
                        az group create -n ${{ vars.AZURE_RG }} -l ${{ vars.LOCATION }}

            - name: Run ARM deployment
              uses: azure/arm-deploy@v1
              with:
                resourceGroupName: ${{ vars.AZURE_RG }}
                template: https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/quickstarts/microsoft.web/webapp-custom-deployment-slots/azuredeploy.json
                parameters: baseResourceName=${{ vars.APP_NAME }} appSettingName=${{ vars.APP_NAME }}