name: Build and deploy .NET 7.0 app to Azure App Service 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          DOTNET_VERSION: '7.0.x'
        steps:
            - uses: actions/checkout@v3

            - name: Set up .NET 
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
    
            - name: Build with dotnet
              run: |
                cd dotnetapp
                dotnet build --configuration Release
    
            - name: dotnet publish
              run: |
                cd dotnetapp
                dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/dotnetapp
    
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                name: sampleapp
                path: ${{env.DOTNET_ROOT}}/dotnetapp
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                name: dotnetapp

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{ vars.APP_NAME}}
                slot-name: 'Dev'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
                package: .